spring.application.name=hackathon-backend
server.port=${PORT:8080}
# DATABASE CONFIGURATION
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT CONFIGURATION
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}



#spring.application.name=hackathon-backend
#server.port=8081
#
## ========================
## DATABASE CONFIG (LOCAL & PROD)
## ========================
#spring.datasource.url=jdbc:postgresql://localhost:5432/hackathon_db
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.datasource.driver-class-name=org.postgresql.Driver
#
## ========================
## JPA / HIBERNATE
## ========================
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#
## ========================
## JWT CONFIG
## ========================
#jwt.secret=mysecretkey123456789
#jwt.expiration=86400000
#
## ========================
## LOGGING (OPTIONAL)
## ========================
#logging.level.org.springframework.security=DEBUG