spring.application.name=hackathon-backend

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/evnovadb
spring.datasource.username=postgres
spring.datasource.password=2005
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#SECURITY configuration
spring.security.user.name=user
spring.security.user.password=123